# Generated by Django 5.2.4 on 2025-07-22 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phonenumber',
            options={'verbose_name': 'Phone Number', 'verbose_name_plural': 'Phone Numbers'},
        ),
        migrations.AlterUniqueTogether(
            name='phonenumber',
            unique_together={('contact', 'type')},
        ),
    ]
