# Generated by Django 5.2.4 on 2025-07-22 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_phonenumber_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestContact',
            new_name='Contact',
        ),
    ]
